trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  ServiceConnectionName: "SPiurALZ"
  ManagementGroupPrefix: "alz"
  TopLevelManagementGroupDisplayName: "Azure Landing Zones"
  Location: "canadacentral"
  LoggingSubId: "de173830-a0f7-43a7-8a5e-a1a752915996"
  LoggingResourceGroupName: "alz-logging"
  HubNetworkSubId: "38a380bc-2acf-4c50-aacb-9f9377f47f02"
  HubNetworkResourceGroupName: "Hub_Networking"
  RoleAssignmentManagementGroupId: "alz-platform"
  SpokeNetworkSubId: "7fbfadc5-a4c7-4617-8f3e-a33afb3292da"
  SpokeNetworkResourceGroupName: "alz-canadacentral-spoke-networking"
  RunNumber: $(Build.BuildNumber)

jobs:
- job:
  steps:

- task: AzureCLI@2
    displayName: Az CLI Deploy Spoke Network Resource Group
    name: create_spoke_network_rg
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az account set --subscription $(SpokeNetworkSubId)
        az deployment sub create \
        --template-file infra-as-code/bicep/modules/resourceGroup/resourceGroup.bicep \
        --parameters parResourceGroupName=$(SpokeNetworkResourceGroupName) parLocation=$(Location) \
        --location $(Location) \
        --name create_spoke_network_rg-$(RunNumber)
        
  - task: AzureCLI@2
    displayName: Az CLI Deploy Spoke Network
    name: create_spoke_network
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az account set --subscription $(SpokeNetworkSubId)
        az deployment group create \
        --resource-group $(SpokeNetworkResourceGroupName) \
        --template-file infra-as-code/bicep/modules/spokeNetworking/spokeNetworking.bicep \
        --parameters @infra-as-code/bicep/modules/spokeNetworking/parameters/spokeNetworking.parameters.all.json \
        --name create_spoke_network-$(RunNumber)
        
  - task: AzureCLI@2
    displayName: Az CLI Deploy Role Assignment
    name: create_role_assignment
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment mg create \
        --template-file infra-as-code/bicep/modules/roleAssignments/roleAssignmentManagementGroupMany.bicep \
        --parameters @infra-as-code/bicep/modules/roleAssignments/parameters/roleAssignmentManagementGroupMany.securityGroup.parameters.all.json \
        --location $(Location) \
        --management-group-id $(RoleAssignmentManagementGroupId) \
        --name create_role_assignment-$(RunNumber)

  - task: AzureCLI@2
    displayName: Deploy Default Policy Assignments
    name: create_policy_assignments
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment mg create \
        --template-file infra-as-code/bicep/modules/policy/assignments/alzDefaults/alzDefaultPolicyAssignments.bicep \
        --parameters @infra-as-code/bicep/modules/policy/assignments/alzDefaults/parameters/alzDefaultPolicyAssignments.parameters.all.json \
        --location $(Location) \
        --management-group-id $(ManagementGroupPrefix) \
        --name create_policy_assignments-$(RunNumber)
